services:
  mongodb:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3360:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pratik00t@
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql