CREATE TABLE 'T_ORDERS'
{
    'ID' BIGINT(20) NOT NULL AUTO_INCREMENT,
    'ORDER-NUMBER' VARCHAR(255) DEFAULT NULL,
    'SKU_CODE' VARCHAR(255),
    'PRICE' DECIMAL(19,2),
    'QUANTITY' INT(11),
    PRIMARY KEY('ID') 
};